### ISSUE TITLE
Better packages caching: add a volume for packages

### ISSUE THREAD

**Issue by ShuP1** [Jomik/screeps-server#27]
Super container 🎉
I like the packages caching feature but it can be even better

When recreating the container (after a `docker compose down` for example), packages are downloaded ones more

It could be avoided by arranging files to allow a "packages" volumes containing `node_modules`, `package.json` and all

Unless creating a volume on `/screeps` is safe, but I donc think so

**Comment by ShuP1** [comment]
Just checked, in fact just adding `/screeps/mods` volume in the docker-compose.yml is enough

So it is probably more note to add in the wiki than a feature

**Comment by Jomik** [comment]
Thanks!

> Just checked, in fact just adding `/screeps/mods` volume in the docker-compose.yml is enough
> 
> So it is probably more note to add in the wiki than a feature

Yeah, this is true. I was thinking of creating a separate volume for mods, or putting them in `/data`. But unsure if it really is that beneficial.
I suppose we can add that note for now.
