### ISSUE TITLE
Pinned packages not supported

### ISSUE THREAD

**Issue by CarsonBurke** [Jomik/screeps-server#3]
Pinned packages is needed to properly manage some dependencies that otherwise fail because of the (necessary) old node version

**Comment by Jomik** [comment]
I would definitely like to support this - would have been easier with a newer version of npm of course 😂 
npm does not have a `resolutions` field, and their `overrides` field is in npm 8.

Do you have an example of when this fails? It works fine for me when I try to launch a fresh image/container with the config from this repository. Would like to have the case at hand to test against, as I probably need to edit the lockfile.

**Comment by Jomik** [comment]
This should be fixed with https://github.com/ScreepsMods/screepsmod-auth/pull/35
I do not think the other 2 recommended pins are needed for this server image. Please come back if the are.
Do need #5 to easily support `resolutions` if we want to...
