### ISSUE TITLE
Storage Process Error when start

### ISSUE THREAD

**Issue by whatIsBest99** [Jomik/screeps-server#98]
The container showed some error and stopped during the starting period. I'm not sure what's going on as I haven't change the content of docker-compose.yml. The error is shown as follows:
<img width="905" alt="Screenshot 2024-05-19 at 9 43 37 PM" src="https://github.com/Jomik/screeps-server/assets/19471266/3b671e5d-6c4b-40f6-a223-430ea8fe7812">

**Comment by Jomik** [comment]
Can you attach your `docker-compose.yml` and config.yml ?
Also would be nice with the logs from within the container.
You can access them with `docker compose exec screeps sh`. Then they should be in the `/screeps/logs` folder.

**Comment by whatIsBest99** [comment]
As I redownloaded and reinitialized the images, the error seems to be gone and it's working now. Sorry for bothering!
